{
 "title": "Workload Analysis Sar Dashboard",
 "time": { "from": "2020-12-07T23:52:34.440Z", "to": "2020-12-09T00:10:09.453Z" },
 "templating": {
  "list": [
   {
    "name": "v_group_name",
    "label": "Host Group",
    "query": "SELECT name FROM groups ORDER BY 1;"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 22, "x": 0, "y": 0 },
   "content": "\n# Greenplum Cluster Performance\n\nPurpose is to identify _possible_ bottlenecks and _possibly_ failing hardware but __ALSO__ potential opportunities.\n\nAll information and interpretation should be used as a guide to streamline an architectural and performance analysis.\n\nOpportunities may be a mostly idle cluster during off hours when rollups, ETL jobs, or materialized views may be created alleviating work hour loads.\n\n\n\n",
   "targets": [
    {
     "select": [
      [
       { "params": [ "value" ], "type": "column" }
      ]
     ],
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      }
     ]
    }
   ]
  },
  {
   "title": "Group Summary",
   "type": "table",
   "gridPos": { "h": 6, "w": 22, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT * FROM public.summary WHERE group_name = '$v_group_name' ORDER BY 1, 2"
    }
   ]
  },
  {
   "title": "Host-Data Volume Average Read & Write",
   "type": "table",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT hostname, device, avg(rd_sec_psec)/2 AS avg_read_k_psec, avg(wr_sec_psec)/2 AS avg_write_k_psec\n  FROM disk_stats_v\n WHERE device IN ( SELECT ga.val FROM group_attribs ga JOIN groups g ON (ga.group_id=g.id) WHERE g.name = '$v_group_name' AND ga.name ~'^datavol' )\n   AND group_name = '$v_group_name'\n   AND master = 'f'\n   AND $__timeFilter(ts)\n GROUP BY 1, 2\n ORDER BY 1, 2;"
    }
   ]
  },
  {
   "title": "Disk Underperformers < 20% of current Avg %Util (Potential Skew / Failing Hardware)",
   "type": "table",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "WITH src AS (\nSELECT hostname, date_trunc('minute',ts) AS ts, device, rd_sec_psec/2 AS rd_kb_psec, wr_sec_psec/2 AS wr_kb_psec, await, util_pct\n  FROM disk_stats_v\n WHERE device IN ( SELECT ga.val FROM group_attribs ga JOIN groups g ON (ga.group_id=g.id) WHERE g.name = '$v_group_name' AND ga.name ~'^datavol' )\n   AND master = 'f'\n   AND $__timeFilter(ts)\n   AND group_name = '$v_group_name'\n\n), avg_utils AS (\nSELECT d.ts, d.hostname, d.device, avg(d.util_pct)\n  FROM src d\n GROUP BY\n   GROUPING SETS ( (1, 2, 3), (d.ts) )\n ORDER BY 1, 2, 3\n), outliers AS (\nSELECT ts1.ts, ts2.hostname, ts2.device, ts1.avg AS period_avg\n     , CASE WHEN ts1.avg > ts2.avg then '>' ELSE '<' END AS op\n     , ts2.avg\n  FROM (SELECT ts,avg FROM avg_utils WHERE hostname IS NULL) AS ts1\n       JOIN\n       (SELECT * FROM avg_utils WHERE hostname IS NOT NULL) AS ts2\n       ON (ts1.ts = ts2.ts)\n WHERE ts2.avg < (0.8 * ts1.avg)\n ORDER BY 2, 3, 1\n), totals AS (\n  SELECT s.hostname, s.device, count(*) FROM src s GROUP BY 1,2\n)\nSELECT o.hostname, o.device\n     , count(DISTINCT format('%s %s %s',o.ts,o.hostname,o.device)) AS outlier_count\n     , s.count AS total_count\n  FROM totals s LEFT JOIN outliers o ON (s.hostname = o.hostname AND s.device = o.device)\n WHERE o.hostname IS NOT NULL\n GROUP BY 1, 2, 4\n ORDER BY 3\n;\n"
    }
   ]
  },
  {
   "title": "Disk Over Utilized > 20% of current Avg %Util (Potential Skew / Failing Hardware)",
   "type": "table",
   "gridPos": { "h": 10, "w": 10, "x": 11, "y": 21 },
   "targets": [
    {
     "rawSql": "WITH src AS (\nSELECT hostname, date_trunc('minute',ts) AS ts, device, rd_sec_psec/2 AS rd_kb_psec, wr_sec_psec/2 AS wr_kb_psec, await, util_pct\n  FROM disk_stats_v\n WHERE device IN ( SELECT ga.val FROM group_attribs ga JOIN groups g ON (ga.group_id=g.id) WHERE g.name = '$v_group_name' AND ga.name ~'^datavol'  )\n   AND master = 'f'\n   AND $__timeFilter(ts)\n   AND group_name = '$v_group_name'\n\n), avg_utils AS (\nSELECT d.ts, d.hostname, d.device, avg(d.util_pct)\n  FROM src d\n GROUP BY\n   GROUPING SETS ( (1, 2, 3), (d.ts) )\n ORDER BY 1, 2, 3\n), outliers AS (\nSELECT ts1.ts, ts2.hostname, ts2.device, ts1.avg AS period_avg\n     , CASE WHEN ts1.avg > ts2.avg then '>' ELSE '<' END AS op\n     , ts2.avg\n  FROM (SELECT ts,avg FROM avg_utils WHERE hostname IS NULL) AS ts1\n       JOIN\n       (SELECT * FROM avg_utils WHERE hostname IS NOT NULL) AS ts2\n       ON (ts1.ts = ts2.ts)\n WHERE ts2.avg > (1.2 * ts1.avg)\n ORDER BY 2, 3, 1\n), totals AS (\n  SELECT s.hostname, s.device, count(*) FROM src s GROUP BY 1,2\n)\nSELECT o.hostname, o.device\n     , count(DISTINCT format('%s %s %s',o.ts,o.hostname,o.device)) AS outlier_count\n     , s.count AS total_count\n  FROM totals s LEFT JOIN outliers o ON (s.hostname = o.hostname AND s.device = o.device)\n WHERE o.hostname IS NOT NULL\n GROUP BY 1, 2, 4\n ORDER BY 3\n;\n"
    }
   ]
  },
  {
   "title": "Average Daily Disk %Util & Average + 1st Deviation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "WITH stats AS (\nSELECT\n  date_trunc('day', d.ts) AS \"time\",\n  stddev(d.util_pct) AS stddev_util_pct,\n  avg(d.util_pct) AS avg_util_pct\nFROM disk_stats_v d JOIN groups g ON (d.group_name = g.name) JOIN group_attribs ga ON (g.id = ga.group_id)\nWHERE\n  ga.name ~ '^datavol'\n  AND d.device = ga.val\n  AND group_name = '$v_group_name'\n  AND d.master = 'f'\n  AND $__timeFilter(d.ts)\n  AND extract('hour' from d.ts) BETWEEN 8 AND 17\nGROUP BY 1\n)\nSELECT \"time\"\n    -- , round(stddev_util_pct::numeric, 2) AS stddev_util_pct\n     , round(avg_util_pct::numeric, 2) AS avg_util_pct\n     , CASE WHEN stddev_util_pct + avg_util_pct < 100.00 THEN round((stddev_util_pct + avg_util_pct)::numeric, 2)\n            ELSE 100.00\n       END AS avg_plus_1dev\n  FROM stats\nORDER BY 1;\n"
    }
   ]
  },
  {
   "title": "Overall Cluster Disk %Util between 8am and 5pm daily",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "\nWITH stats AS (\nSELECT\n  date_trunc('day', d.ts) AS \"time\",\n  stddev(d.util_pct) AS stddev_util_pct,\n  avg(d.util_pct) AS avg_util_pct\nFROM disk_stats_v d JOIN groups g ON (d.group_name = g.name) JOIN group_attribs ga ON (g.id = ga.group_id)\nWHERE\n  ga.name ~ '^datavol'\n  AND d.device = ga.val\n  AND group_name = '$v_group_name'\n  AND d.master = 'f'\n  AND $__timeFilter(d.ts)\n  AND extract('hour' from d.ts) BETWEEN 8 AND 17\nGROUP BY 1\n)\nSELECT \"time\"\n     , round(avg_util_pct::numeric, 2) AS avg_util_pct\n     , CASE WHEN stddev_util_pct + avg_util_pct < 100.00 THEN round((stddev_util_pct + avg_util_pct)::numeric, 2)\n            ELSE 100.00\n       END AS avg_plus_1dev\n  FROM stats\nORDER BY 1;\n\n"
    }
   ]
  },
  {
   "title": "Overall Cluster Disk Read/Write",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(ts,$__interval),\n  sum(bread_psec) AS \"bread_psec\",\n  sum(bwrtn_psec) AS \"bwrite_psec\"\nFROM disk_io_v\nWHERE $__timeFilter(ts)\n  AND group_name = '$v_group_name'\n  AND master = 'f'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Disk Utilization (max% = # hosts x # datavols)",
   "type": "graph",
   "description": "Percentage of elapsed time during which I/O requests were issued to the  device  (bandwidth  utilization for the device). Device saturation occurs when this value is close to 100%.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "\nSELECT\n  d.ts AS \"time\",\n  d.hostname||':'||d.device AS metric,\n  d.util_pct\nFROM disk_stats_v d\nWHERE\n  $__timeFilter(d.ts)\n  AND d.device IN ( SELECT ga.val FROM group_attribs ga JOIN groups g ON (ga.group_id=g.id) WHERE g.name = '$v_group_name' AND ga.name ~'^datavol' )\n  AND group_name = '$v_group_name'\n  AND master = 'f'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Loadavg1 compared to \"max\" and blocked processes",
   "type": "graph",
   "description": "Max = cores * hosts * 0.9 (reserved for OS)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "WITH core_count AS (\nSELECT count(distinct core) - 1 AS tally\n  FROM cpu_v\n WHERE group_name = '$v_group_name'\n   AND core != 'all'\n   AND master = 'f'\n), host_count AS (\nSELECT count(*) AS tally\n  FROM group_host gh JOIN groups g ON (g.id = gh.group_id) JOIN hosts h ON (gh.host_id = h.id)\n WHERE g.name = '$v_group_name'\n   AND h.master = 'f'\n)\nSELECT date_trunc('minute',ts) AS \"time\"\n     , sum(ldavg_1) AS ldavg_1_sum\n     , (h.tally * c.tally * 0.9) AS max_loadavg\n     , sum(blocked) AS blocked\n  FROM loadavg_v, core_count c, host_count h\n WHERE $__timeFilter(ts)\n AND group_name = '$v_group_name'\n AND master = 'f'\n GROUP BY 1, 3\n ORDER BY 1;\n"
    }
   ]
  },
  {
   "title": "Disk Request Wait Time (ms)",
   "type": "graph",
   "description": "The average time (in milliseconds) for I/O requests issued to the device to be served. This includes the time spent by the requests in queue and the time spent servicing them.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  d.ts AS \"time\",\n  d.hostname||':'||d.device AS metric,\n  d.await\nFROM disk_stats_v d\nWHERE\n  $__timeFilter(d.ts) AND d.device IN ( SELECT ga.val FROM group_attribs ga JOIN groups g ON (ga.group_id=g.id) WHERE g.name = '$v_group_name' AND ga.name ~'^datavol' )\n  AND group_name = '$v_group_name'\n  AND master = 'f'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Disk Request Wait Time (ms) compared to Blocked Processes",
   "type": "graph",
   "description": "The average time (in milliseconds) for I/O requests issued to the device to be served. This includes the time spent by the requests in queue and the time spent servicing them.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "WITH disk AS (\n  SELECT date_trunc('minute',ts) AS \"time\", sum(await) AS await FROM disk_stats_v d \n  WHERE device IN (SELECT ga.val FROM group_attribs ga JOIN groups g ON (ga.group_id=g.id) WHERE g.name = '$v_group_name' AND ga.name ~'^datavol')\n     AND $__timeFilter(ts)\n     AND group_name = '$v_group_name'\n     AND master = 'f'\n  GROUP BY 1\n), loadavg AS (\n  SELECT date_trunc('minute',ts) AS \"time\", sum(blocked) AS blocked FROM loadavg_v\n   WHERE $__timeFilter(ts)\n   AND group_name = '$v_group_name'\n   AND master = 'f'\n  GROUP BY 1\n)\nSELECT d.time AS \"time\", d.await, l.blocked\n  FROM disk d JOIN loadavg l ON (d.time = l.time)\nORDER BY d.time;\n"
    }
   ]
  },
  {
   "title": "Overall Cluster Disk Read/Write compared to Network RX errors",
   "type": "graph",
   "description": "rxerr - Total number of bad packets received per second\nrxfifo - Number of FIFO overrun errors that happened per second on received packets",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(d.ts,$__interval),\n  sum(d.bread_psec) AS \"bread_psec\",\n  sum(d.bwrtn_psec) AS \"bwrite_psec\",\n  sum(n.rxerr_psec) AS \"rxerr_psec\",\n  sum(n.rxfifo_psec) AS \"rxfifo_psec\"\nFROM disk_io_v d JOIN network_errors_v n ON (d.ts = n.ts AND d.host_id = n.host_id)\nWHERE\n  $__timeFilter(d.ts)\n  AND n.interface = (SELECT ga.val FROM group_attribs ga JOIN groups g ON (ga.group_id=g.id) WHERE g.name='$v_group_name' AND ga.name='net.interconnect')\n  AND d.group_name = '$v_group_name'\n  AND n.group_name = '$v_group_name'\n  AND d.master = 'f'\n  AND n.master = 'f'\nGROUP BY 1\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Overall Cluster Disk Read/Write compared to Loadavg 1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(d.ts,$__interval),\n  sum(d.bread_psec) AS \"bread_psec\",\n  sum(d.bwrtn_psec) AS \"bwrite_psec\",\n  sum(l.ldavg_1) AS \"ldavg_1\",\n  sum(l.blocked) AS \"blocked\"\nFROM disk_io_v d JOIN loadavg_v l ON (d.ts = l.ts AND d.host_id = l.host_id)\nWHERE\n  $__timeFilter(d.ts)\n  AND d.group_name = '$v_group_name'\n  AND l.group_name = '$v_group_name'\n  AND d.master = 'f'\n  AND l.master = 'f'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  }
 ]
}